apiVersion: v1
kind: Namespace
metadata:
  name: feedlawywer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedlawywer
  namespace: feedlawywer
spec:
  selector:
    matchLabels:
      app: feedlawywer
  template:
    metadata:
      labels:
        app: feedlawywer
    spec:
      containers:
      - name: feedlawywer
        image: felipenoguez/feedlawyer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: feedlawywer-service
  namespace: feedlawywer
spec:
  selector:
    app: feedlawywer
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-feedlawywer
  namespace: feedlawywer
spec:
  ingressClassName: nginx
  rules:
    - host: feedlawywer.eazyacademy.com.br
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: feedlawywer-service
                port:
                  number: 80

